esphome:
  name: scd41demo

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: VERBOSE
  
# api:
#   encryption:
#     key: "BntVVPNZbPNC5UzN9oL4XDDXj6xtatU7aVjumB4EJwY="

ota:
  password: "585353d758e3f126d2f4982f0695d956"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ap:
#   ssid: "Scd41 Hotspot"
#   password: "g0MuFWdXxO2k"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  # scan: true
  # id: bus_a

sensor:
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
    temperature:
      name: "SCD41 Temperature"
    humidity:
      name: "SCD41 Humidity"