esphome:
  name: esp18

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "18T6rbg6kRjpusDhj2opiK2Rr9jksMd7ikNJ7IwsSeE="

ota:
  password: "fb03e5760aa71932dc8e6cda63ed884d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp18 Fallback Hotspot"
    password: "CcQpyx5dWMJy"

captive_portal:

# Per Default ist die On-Board-Led die Statusled und damit für uns nicht mehr nutzbar
# Statusled wird ins "Leere" auf GPIO04 gelegt
# !!! Ist ihm aber egal
# status_led:
#   pin: GPIO4

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

binary_sensor:
  - platform: gpio
    pin: 25
    name: "esp18 motion"
    device_class: motion
sensor:
  - platform: dht
    model: DHT22
    pin: 27
    temperature:
      name: "esp18 temperature"
    humidity:
      name: "esp18 humidity"
    update_interval: 10s

light:
  - platform: status_led
    name: "esp18 led"
    pin: GPIO2 