substitutions:
  name: "iot_yourname"

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

ota:
  - platform: esphome
    password: "88ae8b5aa62702363d12036264178ce9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0min

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  port: !secret mqtt_port

captive_portal:

light:
  - platform: rgb
    name: "${name} RGB Lights"
    id: rgblights
    # unique_id: "6164f726-cfa8-43f5-bd03-a3eba460cea1"
    red: r
    green: g
    blue: b

output:
  - platform: ledc
    pin: GPIO18
    id: r
  - platform: ledc
    pin: GPIO17
    id: g
  - platform: ledc
    pin: GPIO19
    id: b
