esphome:
  name: kerui

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "09T6rbg6kRjpusDhj2opiK2Rr9jksMd7ikNJ7IwsSeE="

ota:
  password: "fb03e5760aa71932dc8e6cda63ed884d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "kerui Fallback Hotspot"
    password: "CcQpyx5dWMJy"

captive_portal:

# Per Default ist die On-Board-Led die Statusled und damit für uns nicht mehr nutzbar
# Statusled wird ins "Leere" auf GPIO04 gelegt
# !!! Ist ihm aber egal
# status_led:
#   pin: GPIO4

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

uart:
  rx_pin: GPIO13
  tx_pin: GPIO12
  baud_rate: 9600

sensor:
  - platform: bme280
    temperature:
      name: "kerui_temperature"
      oversampling: 16x
    pressure:
      name: "kerui_pressure"
    humidity:
      name: "kerui_humidity"
    address: 0x76
    update_interval: 10s

  - platform: mhz19
    co2:
      name: "kerui_co2"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 20s
    automatic_baseline_calibration: false

  - platform: tsl2591
    name: "luminosity"
    id: "my_tls2591"
    address: 0x29
    update_interval: 10s
    gain: auto
    device_factor: 53
    glass_attenuation_factor: 14.4
    visible:
      name: "kerui visible light"
    infrared:
      name: "kerui infrared light"
    full_spectrum:
      name: "kerui full spectrum light"
    calculated_lux:
      id: i_lux
      name: "kerui Lux"

binary_sensor:
  - platform: gpio
    pin: 25
    name: "kerui motion"
    device_class: motion

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO27
    num_leds: 1
    name: "kerui_neopixel_light"